### Create Child Profile
@baseUrl = https://localhost:7089

POST https://localhost:7089/api/ChildProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZW5nYXlhIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJlbmdheWEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJlbmdheWFtb2hhbWVkMjNAZ21haWwuY29tIiwiUGhvbmVOdW1iZXIiOiIwMTA5ODc2NTQzMiIsIklkIjoiMTEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzc3MDM0NTU0LCJpc3MiOiJTY2hvb2xQcm9qZWN0IiwiYXVkIjoiV2ViU2l0ZSJ9.HIZaIKsKjSg10nUaU2JAQezIPmG1Df_ydI2JL01r4nM

{
  "nickname": " salem",
  "ageInYears": 5,
  "ageInMonths": 3,
  "gender": 1,
  "supportNeedsLevel": 2,
  "mainDailyChallengesJson": "[\"sensory sensitivities\", \"\", \"communication\"]",
  "strengthsAndInterests": "Drawing, music, and playing with cars",
  "prefersVisualSchedules": true,
  "communicationMethodsJson": "[\"PECS\", \"Speech\", \"Tablet AAC\"]"
}

